<a href="https://colab.research.google.com/github/Allan19k/Machine-Learning/blob/main/Copia_de_Unidad_1_Repaso_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Título: Álgebra Lineal en Python: Vectores, Matrices y Arreglos**
**1. Introducción**

**Objetivo**: Breve explicación de la importancia de los vectores y matrices en Machine Learning. Introducción a la librería NumPy para manipulación de matrices y arreglos.

In [2]:
import numpy as np

---
**2. Creación de Vectores y Matrices**

Creación de vectores y matrices usando np.array()

In [7]:
# Crear un vector y una matriz
v = np.array([1, 2, 4])
A = np.array([[1, 2], [3, 4]])
print("Vector v:")
print(v)

print("\nMatriz A:")
print(A)


Vector v:
[1 2 4]

Matriz A:
[[1 2]
 [3 4]]


---
**3. Operaciones Básicas con Matrices**

Suma, resta, multiplicación y división de matrices.
Multiplicación escalar.
    
**Operador** @  Multiplicación de matrices (Producto matricial)

Realiza la multiplicación de matrices convencional de álgebra lineal.
Sigue la regla de multiplicación de matrices: la cantidad de columnas de la primera matriz debe ser igual a la cantidad de filas de la segunda.
Es equivalente a la función **np.dot() o np.matmul()**



$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
(1\cdot5 + 2\cdot7) & (1\cdot6 + 2\cdot8) \\
(3\cdot5 + 4\cdot7) & (3\cdot6 + 4\cdot8)
\end{bmatrix}
=
\begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
$$


   **Operador** *: Multiplicación elemento a elemento (Producto Hadamard)

  Realiza una multiplicación punto a punto de los elementos correspondientes de ambas matrices.
  Las matrices deben tener las mismas dimensiones para realizar la operación.
  Es equivalente a la función **np.multiply()**

$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\circ
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
1 \cdot 5 & 2 \cdot 6 \\
3 \cdot 7 & 4 \cdot 8
\end{bmatrix}
=
\begin{bmatrix}
5 & 12 \\
21 & 32
\end{bmatrix}
$$

In [8]:
B = np.array([[5, 6], [7, 8]])
C = A + B  # Suma
D = A @ B  # Multiplicación de matrices
E = A * 2  # Multiplicación escalar

# Impresión con etiquetas
print("Matriz A:")
print(A)

print("\nMatriz B:")
print(B)

print("\nSuma de matrices (A + B):")
print(C)

print("\nMultiplicación de matrices (A @ B):")
print(D)

print("\nMultiplicación escalar de A por 2 (A * 2):")
print(E)


Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]

Suma de matrices (A + B):
[[ 6  8]
 [10 12]]

Multiplicación de matrices (A @ B):
[[19 22]
 [43 50]]

Multiplicación escalar de A por 2 (A * 2):
[[2 4]
 [6 8]]


🟡 Ejercicio:
Implementa la suma y resta de matrices de dimensiones 2x2 generadas aleatoriamente.



In [5]:
# crear matriz
arr1= np.random.randint(0,100,size=(2,2))
print("\nMatriz 1")
print(arr1)

arr2= np.random.randint(0,100,size=(2,2))
print("\nMatriz 2")
print(arr2)

# Implementaciones
Suma = arr1+ arr2
Resta = arr1 - arr2

# Imprimir matrices

print("\nSuma de matrices:")
print(Suma)
print("\nResta de matrices:")
print(Resta)



Matriz 1
[[47 49]
 [97 37]]

Matriz 2
[[99 38]
 [46 14]]

Suma de matrices:
[[146  87]
 [143  51]]

Resta de matrices:
[[-52  11]
 [ 51  23]]


---
**4. Transpuesta, Determinante y Traza**


**a. Transpuesta de una matriz**
La **transpuesta** de una matriz \( A \) es una nueva matriz, denotada como  $$A^T$$ obtenida intercambiando las filas por columnas.

 **Definición:**
Si \( A \) es una matriz de tamaño \( m x n \):

$$
A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
$$

La transpuesta \( A^T \) se define como:

$$
A^T =
\begin{bmatrix}
a_{11} & a_{21} & \cdots & a_{m1} \\
a_{12} & a_{22} & \cdots & a_{m2} \\
\vdots & \vdots & \ddots & \vdots \\
a_{1n} & a_{2n} & \cdots & a_{mn}
\end{bmatrix}
$$

 **Propiedades:**
- la transpuesta de la transpuesta es la matriz original $$(A^T)^T = A $$
- $$ (A + B)^T = A^T + B^T \$$

- $$ (AB)^T = B^T A^T $$


**b. Determinante de una matriz**
El **determinante** de una matriz cuadrada \( A \) (denotado como \( det(A) \) o \( |A| \)) es un valor escalar que proporciona información sobre la invertibilidad de la matriz y el cambio de escala en las transformaciones lineales.

### **Definición:**
Para una matriz \( 2 x 2 \):


A =
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}

El determinante se calcula como:


det(A) = ad - bc


Para matrices de mayor dimensión, se calcula mediante **expansión por cofactores** o métodos numéricos.

### **Propiedades:**
- $$ det(A^T) = det(A) $$
- La matriz no es invertible si $$ det(A) = 0 $$
- $$ det(AB) = det(A) det(B) $$.



**c. Traza de una matriz**
La **traza** de una matriz cuadrada \( A \), denotada como $$ \text{tr}(A) $$ es la suma de los elementos de su diagonal principal.

### **Definición:**
Si \( A \) es una matriz \( n x n \):

$$
A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
$$

La traza se define como:
$$
\
\text{tr}(A) = a_{11} + a_{22} + \cdots + a_{nn}
\
$$
 **Propiedades:**
- $$ \text{tr}(A + B) = \text{tr}(A) + \text{tr}(B) $$
- $$ \text{tr}(cA) = c \, \text{tr}(A) $$ donde  *c* es un escalar.
- $$ \text{tr}(AB) = \text{tr}(BA) $$

---


In [ ]:
A_T = np.transpose(A)  # Transpuesta
det_A = np.linalg.det(A)  # Determinante
trace_A = np.trace(A)  # Traza
print("Matriz A")
print(A)
print("\nMatriz Transpuesta de A")
print(A_T)
print("\nDeterminante de A")
print(det_A)
print("\nTraza de A")
print(trace_A)




Matriz A
[[1 2]
 [3 4]]

Matriz Transpuesta de A
[[1 3]
 [2 4]]

Determinante de A
-2.0000000000000004

Traza de A
5


🟡 Ejercicio:
Calcula la transpuesta, determinante y traza de una matriz 3x3 de tu elección.

In [3]:
# crear matriz
arr3= np.random.randint(0,100,size=(3,3))
print("\nMatriz 3x3")
print(arr3)

#calcular Transpuesta
arr3_T = np.transpose(arr3)

#calcular determinante
det_arr3 = np.linalg.det(arr3)

#calcular traza
trace_arr3 = np.trace(arr3)

#imprimirlas
print("\nTranspuesta de la matriz 3x3")
print(arr3_T)
print("\nDeterminante de la matriz 3x3")
print(det_arr3)
print("\nTraza de la matriz 3x3")
print(trace_arr3)


Matriz 3x3
[[60  7 90]
 [86 90 41]
 [75 81 71]]

Transpuesta de la matriz 3x3
[[60 86 75]
 [ 7 90 81]
 [90 41 71]]

Determinante de la matriz 3x3
182362.99999999994

Traza de la matriz 3x3
221


5. Valores y Vectores Característicos (Eigenvalues y Eigenvectors)

    Introducción a la descomposición de matrices.
    Cálculo con np.linalg.eig.

In [9]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Valores propios de A:")
print(eigenvalues)

print("\nVectores propios de A:")
print(eigenvectors)



Valores propios de A:
[-0.37228132  5.37228132]

Vectores propios de A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


🟡 Ejercicio:
Determina los valores y vectores característicos de una matriz cuadrada 3x3.

In [10]:
arr3_eigenvalues, arr3_eigenvectors = np.linalg.eig(arr3)
print("Valores propios de arr3:")
print(arr3_eigenvalues)

print("\nVectores propios de arr3:")
print(arr3_eigenvectors)
#

Valores propios de arr3:
[198.54403185 +0.j          11.22798407+28.15020282j
  11.22798407-28.15020282j]

Vectores propios de arr3:
[[ 0.45445428+0.j          0.70552842+0.j          0.70552842-0.j        ]
 [ 0.60649738+0.j         -0.48369112-0.29985114j -0.48369112+0.29985114j]
 [ 0.65240496+0.j         -0.3447134 +0.24399696j -0.3447134 -0.24399696j]]
